### ISSUE TITLE
Hey can I get a texture for my Sharp 5 Sword

### ISSUE THREAD

**Issue by Exomi039** [velolib/veloSMP-Official-Resource-Pack#2]
woi lama mana texture gw woi yang diamond sword sharp 5 woi lemot

**Comment by velolib** [comment]
Gw udh add

**Comment by velolib** [comment]
Mesa Prime 
idot

**Comment by Exomi039** [comment]
![reaper_falchion](https://user-images.githubusercontent.com/67255325/85252483-13430c80-b486-11ea-929d-6ac3177f8b14.png)

**Comment by velolib** [comment]
ok thx

**Comment by velolib** [comment]
same name right?

**Comment by Exomi039** [comment]
UMM no

namanya Dranaz

**Comment by velolib** [comment]
okay bye
