### ISSUE TITLE
Diamond Sword Texture | Epical | rasfdh

### ISSUE THREAD

**Issue by rasfdh** [velolib/veloSMP-Official-Resource-Pack#3]
please change my "Epical" sword texture to this thing
![b](https://user-images.githubusercontent.com/67261189/85265608-b99a0c80-b49c-11ea-9c7f-e07e94538aa6.png)

tenks

**Comment by velolib** [comment]
This isn't a texture, it's a screenshot with a white background. Can't add that. Do you have the source website of the image?

**Comment by rasfdh** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pngkey.com%2Fdetail%2Fu2r5q8q8a9a9w7q8_espadadominecraft-espada-minecraft-diamond-sword-minecraft-texture%2F&psig=AOvVaw0RiiWeVHYIgRBHWzluDeRk&ust=1592900680879000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLCMxtP_lOoCFQAAAAAdAAAAABAD

**Comment by rasfdh** [comment]
let me find another etxutuxdtr............

**Comment by rasfdh** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pngjoy.com%2Fpreview%2Fz0l9t7r8r7h9z6_diamond-sword-minecraft-scythe-weapon-texture-pack-hd%2F&psig=AOvVaw0RiiWeVHYIgRBHWzluDeRk&ust=1592900680879000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLCMxtP_lOoCFQAAAAAdAAAAABAb

what about that

**Comment by outrowed** [comment]
@rasfdh its the same thing lol
https://www.pngjoy.com/pngl/152/3044721_diamond-sword-minecraft-scythe-weapon-texture-pack-hd.png

**Comment by outrowed** [comment]
and anyway, is 377x388. the only way to add that texture to the resource pack is manually remaking that texture

**Comment by rasfdh** [comment]
so whats the minimum to make a texture

**Comment by velolib** [comment]
16x16, the maximum is also 16x16

**Comment by outrowed** [comment]
![PngJoy_diamond-sword-minecraft-scythe-weapon-texture-pack-hd_3044721](https://user-images.githubusercontent.com/59441185/85274615-61b5d280-b4a9-11ea-9b28-5a07c43b8d64.png)
![image](https://user-images.githubusercontent.com/59441185/85274647-6bd7d100-b4a9-11ea-8970-b0e622487bf3.png)
i remake the texture for him lol

**Comment by velolib** [comment]
> @rasfdh its the same thing lol
> https://www.pngjoy.com/pngl/152/3044721_diamond-sword-minecraft-scythe-weapon-texture-pack-hd.png

This can't be used

> https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pngjoy.com%2Fpreview%2Fz0l9t7r8r7h9z6_diamond-sword-minecraft-scythe-weapon-texture-pack-hd%2F&psig=AOvVaw0RiiWeVHYIgRBHWzluDeRk&ust=1592900680879000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLCMxtP_lOoCFQAAAAAdAAAAABAb
> 
> what about that

This also can't be used
Yeah, the pack is strictly 16x16, as larger resolutions would:
- Take up more space
- Destroy any continuity between items
- Not fit well with the surroundings

I suggest searching for weapon textures in [Planetminecraft](https://www.planetminecraft.com/) or [Novaskin's Gallery](http://minecraft.novaskin.me/gallery.)
Also please hyperlink links whenever you can.

**Comment by outrowed** [comment]
alright, he said, that he wants animated fire sword
![image](https://user-images.githubusercontent.com/59441185/85276028-62e7ff00-b4ab-11ea-8289-e858209a67a7.png)

**Comment by velolib** [comment]
> alright, he said, that he wants animated fire sword
> ![image](https://user-images.githubusercontent.com/59441185/85276028-62e7ff00-b4ab-11ea-8289-e858209a67a7.png)

I may have a texture for that, but can you please tell him to actually talk to me on the issue and not through you

**Comment by rasfdh** [comment]
ok

**Comment by outrowed** [comment]
i'm talking on github, amrite lads?

**Comment by velolib** [comment]
edit that now

**Comment by outrowed** [comment]
@rasfdh, you must find 16x image of scythe/sword from planetminecraft.com or rip directly of someone resource pack.
Here is an example of an 16x image:
![image](https://user-images.githubusercontent.com/59441185/85277835-397ca280-b4ae-11ea-91b4-d871575ee30c.png)
I know it is small, but minecraft only support 16x to 256x

**Comment by rasfdh** [comment]
something like this idk
https://gyazo.com/c207c8193d42076338efddf3834ef71e

**Comment by outrowed** [comment]
You must share the **raw** 16x image, not that.

**Comment by rasfdh** [comment]
its a fucking example

**Comment by velolib** [comment]
> something like this idk
> https://gyazo.com/c207c8193d42076338efddf3834ef71e

That's.... literally the exact same texture from mirzaholic. It's from a hypixel skyblock texture pack.

**Comment by outrowed** [comment]
Oh, then make JSON file about that image available to rasfdh and mirzaholic. Done!

**Comment by outrowed** [comment]
Or, just ask mirzaholic about that sword image, and put it on the resource pack.

**Comment by velolib** [comment]
> Oh, then make JSON file about that image available to rasfdh and mirzaholic. Done!

No. Each person's textures are for **personal use,** unless they really want to make it public (which mirzaholic probably won't like.) Also, I think it's way better if everyone's texture is different. It makes everyone unique.

**Comment by rasfdh** [comment]
ngggggggggggggi give u p do this instead pls
![image](https://user-images.githubusercontent.com/67261189/85278441-2d451500-b4af-11ea-83be-837b641d7661.png)
![image](https://user-images.githubusercontent.com/67261189/85278444-2d451500-b4af-11ea-9ec4-309f7e209efb.png)
![image](https://user-images.githubusercontent.com/67261189/85278448-2dddab80-b4af-11ea-9e5e-45b0da402c6d.png)
![image](https://user-images.githubusercontent.com/67261189/85278445-2dddab80-b4af-11ea-8728-f9810055f318.png)
![image](https://user-images.githubusercontent.com/67261189/85278449-2dddab80-b4af-11ea-84cf-001ef5e18fce.png)
![image](https://user-images.githubusercontent.com/67261189/85278450-2dddab80-b4af-11ea-91b5-1a88dc3a079b.png)
![image](https://user-images.githubusercontent.com/67261189/85278451-2dddab80-b4af-11ea-9f67-e82a0ee01269.png)
![image](https://user-images.githubusercontent.com/67261189/85278452-2dddab80-b4af-11ea-8475-cb6b2ee3b33b.png)
![image](https://user-images.githubusercontent.com/67261189/85278453-2dddab80-b4af-11ea-89ae-9575bb816bdd.png)
![image](https://user-images.githubusercontent.com/67261189/85278447-2dddab80-b4af-11ea-8162-b86581a3cbcb.png)
![image](https://user-images.githubusercontent.com/67261189/85278446-2dddab80-b4af-11ea-9d76-7da16c6b2c6e.png)
![image](https://user-images.githubusercontent.com/67261189/85278455-2e764200-b4af-11ea-86d5-609b67198dfa.png)
![image](https://user-images.githubusercontent.com/67261189/85278454-2dddab80-b4af-11ea-9f65-a59fa5e08554.png)
![image](https://user-images.githubusercontent.com/67261189/85278456-2e764200-b4af-11ea-9282-05775db29782.png)

**Comment by outrowed** [comment]
Problem solved, close this issue please.

**Comment by velolib** [comment]
> ngggggggggggggi give u p do this instead pls
> ![image](https://user-images.githubusercontent.com/67261189/85278441-2d451500-b4af-11ea-83be-837b641d7661.png)
> ![image](https://user-images.githubusercontent.com/67261189/85278444-2d451500-b4af-11ea-9ec4-309f7e209efb.png)
> ![image](https://user-images.githubusercontent.com/67261189/85278448-2dddab80-b4af-11ea-9e5e-45b0da402c6d.png)
> ![image](https://user-images.githubusercontent.com/67261189/85278445-2dddab80-b4af-11ea-8728-f9810055f318.png)
> ![image](https://user-images.githubusercontent.com/67261189/85278449-2dddab80-b4af-11ea-84cf-001ef5e18fce.png)
> ![image](https://user-images.githubusercontent.com/67261189/85278450-2dddab80-b4af-11ea-91b5-1a88dc3a079b.png)
> ![image](https://user-images.githubusercontent.com/67261189/85278451-2dddab80-b4af-11ea-9f67-e82a0ee01269.png)
> ![image](https://user-images.githubusercontent.com/67261189/85278452-2dddab80-b4af-11ea-8475-cb6b2ee3b33b.png)
> ![image](https://user-images.githubusercontent.com/67261189/85278453-2dddab80-b4af-11ea-89ae-9575bb816bdd.png)
> ![image](https://user-images.githubusercontent.com/67261189/85278447-2dddab80-b4af-11ea-8162-b86581a3cbcb.png)
> ![image](https://user-images.githubusercontent.com/67261189/85278446-2dddab80-b4af-11ea-9d76-7da16c6b2c6e.png)
> ![image](https://user-images.githubusercontent.com/67261189/85278455-2e764200-b4af-11ea-86d5-609b67198dfa.png)
> ![image](https://user-images.githubusercontent.com/67261189/85278454-2dddab80-b4af-11ea-9f65-a59fa5e08554.png)
> ![image](https://user-images.githubusercontent.com/67261189/85278456-2e764200-b4af-11ea-9282-05775db29782.png)

I could add that, but do you really want that? The shading isn't that... great for a sword. Combined with the lower utilities (items are lower on your hands), it'd hardly be visible for the user.

**Please confirm 1 more time of you want this.**

Also, here's a good alternative (I have more):
![lmaodude](https://user-images.githubusercontent.com/62535821/85278665-7006ed00-b4af-11ea-9cfb-f82819b2cdb7.gif)

**Comment by rasfdh** [comment]
send more?

**Comment by outrowed** [comment]
Ohh. That texture seems fit the surrounding and more better than the old one I remade.

**Comment by velolib** [comment]
> send more?

Okay, 1 second.

**Comment by velolib** [comment]
![flaming_sword](https://user-images.githubusercontent.com/62535821/85279063-0b985d80-b4b0-11ea-9860-812d510ea281.png)
![flamesword](https://user-images.githubusercontent.com/62535821/85279070-0c30f400-b4b0-11ea-8f11-8b3995ef59d5.png)
![flamswordt](https://user-images.githubusercontent.com/62535821/85279072-0cc98a80-b4b0-11ea-9046-b130e86d7ebb.png)

**Comment by outrowed** [comment]
Welp, I think my assistance is not needed here anymore. Cya!

**Comment by rasfdh** [comment]
go for this one pls......... 
![image](https://user-images.githubusercontent.com/67261189/85279145-2965c280-b4b0-11ea-90af-8ddbc6dae1d7.png)

**Comment by velolib** [comment]
> go for this one pls.........
> ![image](https://user-images.githubusercontent.com/67261189/85279145-2965c280-b4b0-11ea-90af-8ddbc6dae1d7.png)

confirm 1 more time

**Comment by rasfdh** [comment]
![image](https://user-images.githubusercontent.com/67261189/85279225-44d0cd80-b4b0-11ea-83c3-bce9cfe698f3.png)


PLS

**Comment by rasfdh** [comment]
btw i have an airsfot sniper on my dinner table im gonna shoot my cat brb

**Comment by velolib** [comment]
> btw i have an airsfot sniper on my dinner table im gonna shoot my cat brb

Yeah ok, case closed.
